language: objective-c
osx_image: xcode9
xcode_project: UIDeviceComplete.xcodeproj
xcode_scheme: UIDeviceComplete

script:
  - xcodebuild test -scheme UIDeviceComplete -sdk iphonesimulator -destination 'OS=11.0,name=iPhone 6 Plus'
after_success:
  - bash <(curl -s https://codecov.io/bash)
